#!/usr/bin/env bash
# Render package-manager definitions for one released version.
#
# The formula and PKGBUILD must reference the exact archives a release
# published, so both are generated from that release's own SHA256SUMS rather
# than maintained by hand and hoped to match.
set -euo pipefail

if [[ $# -ne 4 ]]; then
  echo "usage: $0 <version> <sha256sums-file> <repository-slug> <output-directory>" >&2
  exit 2
fi

version="$1"
sums="$2"
repository="$3"
output="$4"
base="https://github.com/${repository}/releases/download/v${version}"

checksum() {
  local target="$1"
  local archive="super-herdr-v${version}-${target}.tar.gz"
  local value
  value="$(awk -v archive="${archive}" '$2 == archive || $2 == "*"archive { print $1; exit }' "${sums}")"
  if [[ -z "${value}" ]]; then
    echo "no checksum for ${archive} in ${sums}" >&2
    exit 1
  fi
  printf '%s' "${value}"
}

macos_arm="$(checksum aarch64-apple-darwin)"
macos_intel="$(checksum x86_64-apple-darwin)"
linux_arm="$(checksum aarch64-unknown-linux-gnu)"
linux_intel="$(checksum x86_64-unknown-linux-gnu)"

mkdir -p "${output}"

cat > "${output}/super-herdr.rb" <<FORMULA
# Generated by scripts/render-packaging.sh for v${version}. Do not edit by hand.
class SuperHerdr < Formula
  desc "Multi-host federation client for Herdr sessions"
  homepage "https://github.com/${repository}"
  version "${version}"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "${base}/super-herdr-v${version}-aarch64-apple-darwin.tar.gz"
      sha256 "${macos_arm}"
    end
    on_intel do
      url "${base}/super-herdr-v${version}-x86_64-apple-darwin.tar.gz"
      sha256 "${macos_intel}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/super-herdr-v${version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${linux_arm}"
    end
    on_intel do
      url "${base}/super-herdr-v${version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${linux_intel}"
    end
  end

  def install
    bin.install "super-herdr"
    doc.install "README.md", "LICENSE-MIT", "LICENSE-APACHE"
  end

  test do
    assert_match "super-herdr #{version}", shell_output("#{bin}/super-herdr --version")
  end
end
FORMULA

cat > "${output}/PKGBUILD" <<PKGBUILD
# Generated by scripts/render-packaging.sh for v${version}. Do not edit by hand.
# Maintainer: Mikro Design <vemund.bakken@onio.com>
pkgname=super-herdr-bin
pkgver=${version}
pkgrel=1
pkgdesc="Multi-host federation client for Herdr sessions"
arch=('x86_64' 'aarch64')
url="https://github.com/${repository}"
license=('MIT' 'Apache-2.0')
provides=('super-herdr')
conflicts=('super-herdr')
source_x86_64=("${base}/super-herdr-v\${pkgver}-x86_64-unknown-linux-gnu.tar.gz")
source_aarch64=("${base}/super-herdr-v\${pkgver}-aarch64-unknown-linux-gnu.tar.gz")
sha256sums_x86_64=('${linux_intel}')
sha256sums_aarch64=('${linux_arm}')

package() {
  local target
  case "\${CARCH}" in
    x86_64) target=x86_64-unknown-linux-gnu ;;
    aarch64) target=aarch64-unknown-linux-gnu ;;
    *) echo "unsupported architecture \${CARCH}" >&2; return 1 ;;
  esac
  local extracted="\${srcdir}/super-herdr-v\${pkgver}-\${target}"
  install -Dm755 "\${extracted}/super-herdr" "\${pkgdir}/usr/bin/super-herdr"
  install -Dm644 "\${extracted}/README.md" "\${pkgdir}/usr/share/doc/\${pkgname}/README.md"
  install -Dm644 "\${extracted}/LICENSE-MIT" "\${pkgdir}/usr/share/licenses/\${pkgname}/LICENSE-MIT"
  install -Dm644 "\${extracted}/LICENSE-APACHE" "\${pkgdir}/usr/share/licenses/\${pkgname}/LICENSE-APACHE"
}
PKGBUILD

# The AUR validates a push against .SRCINFO, not against PKGBUILD, so the two
# must agree. makepkg is not installable on the release runner, so this renders
# the same projection makepkg --printsrcinfo would emit, from the same values.
# The leading dot is dropped because a release asset glob skips hidden files;
# the AUR repository wants it back as .SRCINFO.
cat > "${output}/super-herdr-bin.SRCINFO" <<SRCINFO
pkgbase = super-herdr-bin
	pkgdesc = Multi-host federation client for Herdr sessions
	pkgver = ${version}
	pkgrel = 1
	url = https://github.com/${repository}
	arch = x86_64
	arch = aarch64
	license = MIT
	license = Apache-2.0
	provides = super-herdr
	conflicts = super-herdr
	source_x86_64 = ${base}/super-herdr-v${version}-x86_64-unknown-linux-gnu.tar.gz
	sha256sums_x86_64 = ${linux_intel}
	source_aarch64 = ${base}/super-herdr-v${version}-aarch64-unknown-linux-gnu.tar.gz
	sha256sums_aarch64 = ${linux_arm}

pkgname = super-herdr-bin
SRCINFO

echo "rendered ${output}/super-herdr.rb, ${output}/PKGBUILD, and ${output}/super-herdr-bin.SRCINFO for v${version}"
