#!/usr/bin/env bash
# Render package-manager definitions for one released version.
#
# The formula must reference the exact archives a release published, so it is
# generated from that release's own SHA256SUMS rather than maintained by hand
# and hoped to match.
set -euo pipefail

if [[ $# -ne 4 ]]; then
  echo "usage: $0 <version> <sha256sums-file> <repository-slug> <output-directory>" >&2
  exit 2
fi

version="$1"
sums="$2"
repository="$3"
output="$4"
base="https://github.com/${repository}/releases/download/v${version}"

checksum() {
  local target="$1"
  local archive="super-herdr-v${version}-${target}.tar.gz"
  local value
  value="$(awk -v archive="${archive}" '$2 == archive || $2 == "*"archive { print $1; exit }' "${sums}")"
  if [[ -z "${value}" ]]; then
    echo "no checksum for ${archive} in ${sums}" >&2
    exit 1
  fi
  printf '%s' "${value}"
}

macos_arm="$(checksum aarch64-apple-darwin)"
macos_intel="$(checksum x86_64-apple-darwin)"
linux_arm="$(checksum aarch64-unknown-linux-gnu)"
linux_intel="$(checksum x86_64-unknown-linux-gnu)"

mkdir -p "${output}"

cat > "${output}/super-herdr.rb" <<FORMULA
# Generated by scripts/render-packaging.sh for v${version}. Do not edit by hand.
class SuperHerdr < Formula
  desc "Multi-host federation client for Herdr sessions"
  homepage "https://github.com/${repository}"
  version "${version}"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "${base}/super-herdr-v${version}-aarch64-apple-darwin.tar.gz"
      sha256 "${macos_arm}"
    end
    on_intel do
      url "${base}/super-herdr-v${version}-x86_64-apple-darwin.tar.gz"
      sha256 "${macos_intel}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/super-herdr-v${version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${linux_arm}"
    end
    on_intel do
      url "${base}/super-herdr-v${version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${linux_intel}"
    end
  end

  def install
    bin.install "super-herdr"
    doc.install "README.md", "LICENSE-MIT", "LICENSE-APACHE"
  end

  test do
    assert_match "super-herdr #{version}", shell_output("#{bin}/super-herdr --version")
  end
end
FORMULA

echo "rendered ${output}/super-herdr.rb for v${version}"
